### ISSUE TITLE
0.8.4: "'NoneType' object has no attribute 'rfind'"

### ISSUE THREAD

**Issue by Zamana** [morpheus65535/bazarr#727]
**Describe the bug**
After update to 0.8.4 Legendas.TV has status "TypeError"

**To Reproduce**
1. Install or upgrade to 0.8.4 version with Python 3.6
2. Check System->Providers status

**Expected behavior**
Legendas.TV should has "Good" in the status column.

**Software (please complete the following information):**
 - Bazarr: 0.8.4
 - Radarr version:0.2.0.1358
 - Sonarr version 2.0.0.5338
 - OS: FreeNAS 11.2-U7 (in a jail)
-  Python: 3.6.9

**Additional context**
LOG:
01/01/2020 02:59:57|INFO    |root                            |Throttling legendastv for 10 minutes, until 20/01/01 03:09, because of: AttributeError. Exception info: "'NoneType' object has no attribute 'rfind'"|

**Comment by halali** [comment]
We will need debug log, but i gues legendas.tv dont return valid page.

**Comment by Zamana** [comment]
It was working until the upgrade to 0.8.4.

More info grabbed right now:

Throttling legendastv for 10 minutes, until 20/01/01 15:40, because of: TypeError. Exception info: 'expected str, bytes or os.PathLike object, not NoneType'

**Comment by Zamana** [comment]
[bazarr.log.zip](https://github.com/morpheus65535/bazarr/files/4014442/bazarr.log.zip)
And here is the complete LOG file.

**Comment by halali** [comment]
Clear your log, go to general settings and enable debug logging, after that try to retry steps to issue you have, and after send debug log please.

**Comment by Zamana** [comment]
Thanks for the instructions.

Anyway... in the meantime I installed py36-subliminal (and the bunch of dependencies that it brings with it...), and now the errors are gone.

I'm not sure, but I guess that this was the missing piece...

Thanks.
Regards.

**Comment by faacunha** [comment]
Having the very same issue despite updating the subliminal package, debug log is attached
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4022400/bazarr.log)

**Comment by faacunha** [comment]
@halali and also @Zamana if you would have any other idea

**Comment by Zamana** [comment]
Hi.

I don't know if I can help with this issue. Anyway, here is the complete list of packages I have installed in the Bazarr jail:

`root@bazarr:~ # pkg info
ca_root_nss-3.47.1             Root certificate bundle from the Mozilla Project
curl-7.66.0                    Command line tool and library for transferring data with URLs
cvsps-2.1_2                    Create patchset information from CVS
expat-2.2.8                    XML 1.0 parser written in C
gdbm-1.18.1_1                  GNU database manager
gettext-runtime-0.20.1         GNU gettext runtime libraries and programs
git-2.23.0                     Distributed source code management tool
indexinfo-0.3.1                Utility to regenerate the GNU info page index
libffi-3.2.1_3                 Foreign Function Interface
libgcrypt-1.8.5                General purpose cryptographic library based on the code from GnuPG
libgpg-error-1.36              Common error values for all GnuPG components
libnghttp2-1.39.2              HTTP/2.0 C Library
libxml2-2.9.9                  XML parser library for GNOME
libxslt-1.1.33                 The XSLT C library for GNOME
p5-Authen-SASL-2.16_1          Perl5 module for SASL authentication
p5-CGI-4.44                    Handle Common Gateway Interface requests and responses
p5-Digest-HMAC-1.03_1          Perl5 interface to HMAC Message-Digest Algorithms
p5-Error-0.17028               Error/exception handling in object-oriented programming style
p5-GSSAPI-0.28_1               Perl extension providing access to the GSSAPIv2 library
p5-HTML-Parser-3.72            Perl5 module for parsing HTML documents
p5-HTML-Tagset-3.20_1          Some useful data table in parsing HTML
p5-IO-Socket-INET6-2.72_1      Perl module with object interface to AF_INET6 domain sockets
p5-IO-Socket-SSL-2.066         Perl5 interface to SSL sockets
p5-Mozilla-CA-20180117         Perl extension for Mozilla CA cert bundle in PEM format
p5-Net-SSLeay-1.85             Perl5 interface to SSL
p5-Socket6-0.29                IPv6 related part of the C socket.h defines and structure manipulators
pcre-8.43_2                    Perl Compatible Regular Expressions library
perl5-5.30.0                   Practical Extraction and Report Language
pkg-1.12.0                     Package manager
py36-appdirs-1.4.3             Python module for determining platform-specific dirs
py36-asn1crypto-0.24.0         ASN.1 library with a focus on performance and a pythonic API
py36-babelfish-0.5.5           Module to work with countries and languages
py36-beautifulsoup-4.8.0       HTML/XML Parser for Python
py36-certifi-2019.6.16         Mozilla SSL certificates
py36-cffi-1.12.3               Foreign Function Interface for Python calling C code
py36-chardet-3.0.4_3           Universal encoding detector for Python 2 and 3
py36-click-7.0                 Python package for creating command line interfaces
py36-cryptography-2.6.1        Cryptographic recipes and primitives for Python developers
py36-dateutil-2.8.0            Extensions to the standard Python datetime module
py36-decorator-4.3.0           Better living through Python with decorators
py36-dogpile.cache-0.8.0       Caching front-end based on the Dogpile lock
py36-enzyme-0.4.1_1            Python module to parse metadata in video files
py36-gdbm-3.6.9_6              Python bindings to the GNU dbm library (Python 3.6)
py36-guessit-2.1.4             Extract as much information as possible from a video file
py36-html5lib-1.0.1            Python based HTML parser based on the HTML5 spec
py36-idna-2.8                  Internationalized Domain Names in Applications (IDNA)
py36-libxml2-2.9.9             Python interface for XML parser library for GNOME
py36-lxml-4.3.4_1              Pythonic binding for the libxml2 and libxslt libraries
py36-openssl-19.0.0            Python interface to the OpenSSL library
py36-pbr-3.1.1_1               Python Build Reasonableness
py36-pip-19.1.1                Tool for installing and managing Python packages
py36-pycparser-2.19            C parser in Python
py36-pysocks-1.7.1             Python SOCKS module
py36-pysrt-1.1.1               SubRip (.srt) subtitle parser and writer
py36-pytz-2019.3,1             World Timezone Definitions for Python
py36-rarfile-3.0               Python module for RAR archive reading
py36-rebulk-0.9.0              Python library that performs advanced searches in strings
py36-requests-2.22.0           HTTP library written in Python for human beings
py36-setuptools-41.2.0         Python packages installer
py36-six-1.12.0                Python 2 and 3 compatibility utilities
py36-soupsieve-1.9_1           CSS4 selector implementation for BeautifulSoup
py36-sqlite3-3.6.9_7           Standard Python binding to the SQLite3 library (Python 3.6)
py36-stevedore-1.29.0_1        Manage dynamic plugins for Python applications
py36-subliminal-2.0.5_2        Python library to search and download subtitles
py36-urllib3-1.22,1            HTTP library with thread-safe connection pooling, file post, and more
py36-webencodings-0.5.1        Character encoding aliases for legacy web content
python36-3.6.9_1               Interpreted object-oriented programming language
readline-8.0.0                 Library for editing command lines as they are typed
sqlite3-3.29.0                 SQL database engine in a C library
unrar-5.71_1,6                 Extract, view & test RAR archives
`

**Comment by faacunha** [comment]
Thanks for the pkg list, unfortunately mine still throw the error shown on the log above.

**Comment by morpheus65535** [comment]
I've just tested using `linuxserver/bazarr:development` and it works perfectly fine for me either with/without scenename or using manual or automatic search.

**Comment by faacunha** [comment]
@morpheus65535 does it help you to know I'm running it from a RPI3 with Raspbian 9 (stretch) and using Python 3.8.1?

I mean just to see if you're testing under similar parameters, after all mine was working on Python 2.7 and after I installed 3.8 and made bazarr work on it I'm having this error

**Comment by morpheus65535** [comment]
@faacunha I've dusted my RPi and installed Raspbian 9 on it. Unfortunately, it seems that the latest version of Python available is quite old (3.5.3-1). How did you install Python 3.8.1?

**Comment by faacunha** [comment]
@morpheus65535 I had installed it manually and then set it up as my default python3 version.

Raspbian 10 came out though and I didn't know so I'm using the opportunity to do a clean install on my RPi and since it comes with Python 3.7 out of the box, let's see if Bazarr works out of the box once I install it in the next couple hours, I'll keep you posted before you have any unnecessary work.

Thanks

**Comment by faacunha** [comment]
@morpheus65535 error still happens after a fresh Raspbian 10 (buster) install, very same error as above, just upgrade this RPi of yours to Raspbian 10, which has Python 3.7.3 as default, and try to search for any Subtitles using LegendasTV. The very same `TypeError. Exception info: 'expected str, bytes or os.PathLike object, not NoneType'` is thrown.

Full exception is below: 

`Unexpected error in provider 'legendastv': Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 164, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 100, in __getitem__    provider = provider_registry[name](**self.provider_configs.get(name, {}))  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendastv.py", line 75, in __init__    rarfile.custom_check([rarfile.UNRAR_TOOL], True)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2823, in custom_check    p = custom_popen(cmd)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2812, in custom_popen    p = Popen(cmd, bufsize=0, stdout=PIPE, stdin=PIPE, stderr=STDOUT,  File "/usr/local/lib/python3/subprocess.py", line 854, in __init__    self._execute_child(args, executable, preexec_fn, close_fds,  File "/usr/local/lib/python3/subprocess.py", line 1583, in _execute_child    and os.path.dirname(executable)  File "/usr/local/lib/python3/posixpath.py", line 152, in dirname    p = os.fspath(p)TypeError: expected str, bytes or os.PathLike object, not NoneType|Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 164, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 100, in __getitem__    provider = provider_registry[name](**self.provider_configs.get(name, {}))  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendastv.py", line 75, in __init__    rarfile.custom_check([rarfile.UNRAR_TOOL], True)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2823, in custom_check    p = custom_popen(cmd)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2812, in custom_popen    p = Popen(cmd, bufsize=0, stdout=PIPE, stdin=PIPE, stderr=STDOUT,  File "/usr/local/lib/python3/subprocess.py", line 854, in __init__    self._execute_child(args, executable, preexec_fn, close_fds,  File "/usr/local/lib/python3/subprocess.py", line 1583, in _execute_child    and os.path.dirname(executable)  File "/usr/local/lib/python3/posixpath.py", line 152, in dirname    p = os.fspath(p)TypeError: expected str, bytes or os.PathLike object, not NoneType`

**Comment by morpheus65535** [comment]
@Zamana does solution from #735 fix your issue?

**Comment by Zamana** [comment]
I'm sorry buy I can't say.  I have unrar installed since the beginning, because I know that Legendas.TV compress their files with **rar**. 

What seemed to had solved the issue just after the upgrade to 0.8.4 (and from py27 to py36) was the installation of the subliminal package (I guess...).

Regards.

**Comment by morpheus65535** [comment]
Ok so I'll close this one. Reopen it if required.
