### ISSUE TITLE
Doesn't work with python 3.10 -- import collectors is removed in 3.10

### ISSUE THREAD

**Issue by fryfrog** [morpheus65535/bazarr#1640]
**Describe the bug**
Arch Linux just pushed Python 3.10 to everyone and now Bazarr does not run, complaining that `AttributeError: module 'collections' has no attribute 'MutableMapping'`.

**To Reproduce**
Try to run Bazarr on Python 3.10

**Expected behavior**
It should run! :)

**Software (please complete the following information):**
 - Bazarr: v1.0.1
 - OS: Arch Linux

**Additional context**
A similar issue for Tautulli, https://github.com/Tautulli/Tautulli/issues/1558 which links to a few other issues. I didn't see any actual commits linked, so I'm not *quite* sure of the fix. Might just be importing `collections.abc` or something?

```
fryfrog@apollo ~  ❯ sudo -u bazarr /usr/bin/python /usr/lib/bazarr/bazarr.py --no-update --config /var/lib/bazarr
Bazarr starting...
Traceback (most recent call last):
  File "/usr/lib/bazarr/bazarr/main.py", line 18, in <module>
    from config import settings, url_sonarr, url_radarr, configure_proxy_func, base_url
  File "/usr/lib/bazarr/bazarr/config.py", line 9, in <module>
    from subliminal.cache import region
  File "/usr/lib/bazarr/bazarr/../libs/subliminal/__init__.py", line 12, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/usr/lib/bazarr/bazarr/../libs/subliminal/core.py", line 29, in <module>
    from babelfish import Language, LanguageReverseError
  File "/usr/lib/bazarr/bazarr/../libs/babelfish/__init__.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/usr/lib/bazarr/bazarr/../libs/babelfish/converters/__init__.py", line 6, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
  File "/usr/lib/bazarr/bazarr/../libs/pkg_resources/__init__.py", line 82, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/usr/lib/bazarr/bazarr/../libs/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/usr/lib/bazarr/bazarr/../libs/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/usr/lib/bazarr/bazarr/../libs/pkg_resources/_vendor/pyparsing.py", line 943, in <module>
    collections.MutableMapping.register(ParseResults)
AttributeError: module 'collections' has no attribute 'MutableMapping'
Bazarr exited.
```

**Comment by poneli** [comment]
Use the dev branch. I'm using Fedora 35 with Python 3.10.

**Comment by fryfrog** [comment]
@morpheus65535, sounds like it is already fixed, could you do a new release that includes the fix? :)

**Comment by morpheus65535** [comment]
Latest supported Python version is 3.8.x. Anything newer than that could work but there's no warranty. For now you may use the dev version that should work. There's no ETA for a merge to master branch to make this fix included in stable.

**Comment by fryfrog** [comment]
I'm not primarily asking for myself. I'm asking for all Arch users so the [bazarr aur package](https://aur.archlinux.org/packages/bazarr/) will work again. At least it is already fixed, thanks for that! I'll think about pushing dev to this package if you think it'll be awhile.

**Comment by morpheus65535** [comment]
I should merge it within one or two weeks max.

**Comment by maran** [comment]
> I should merge it within one or two weeks max.

Has this been merged yet? Ubuntu 22.04 comes with Python 3.10 by default so this seems more pressing.
